name: test PR 
on: [pull_request]
   
jobs:
  check:
   runs-on: ubuntu-latest
   defaults:
    run:
     shell: bash
     working-directory: ${{ github.workspace }}/
  
   steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
    - name: Install dependencies
      run: go mod download
    - name: Run tests
      run: |
        echo "Running tests"
        go test -v ./...